#index:
#    path: /
#    controller: App\Controller\DefaultController::index
test:
    path: /test
    controller: App\Controller\TestController::index
frontend:
    path: /frontend
    controller: App\Controller\FrontendController::index
vue:
    path: /vue
    controller: App\Controller\FrontendController::vue
select:
    path: /select
    controller: App\Controller\DoctrineController::select
update:
    path: /update
    controller: App\Controller\DoctrineController::update
delete:
    path: /delete
    controller: App\Controller\DoctrineController::delete
insert:
    path: /insert
    controller: App\Controller\DoctrineController::insert
trt:
    path: /trt
    controller: App\Controller\OopController::trt
redis:
    path: /redis
    controller: App\Controller\RedisController::index
cookies:
    path: /cookies
    controller: App\Controller\ResourcesController::cookies
session:
    path: /session
    controller: App\Controller\ResourcesController::session
currency-api:
    path: /currency
    controller: App\Controller\CurrencyController::index
strict:
    path: /strict
    controller: App\Controller\StrictController::index
magic:
    path: /magic
    controller: App\Controller\MagicController::index
